import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const files = dir => fs.readdirSync(path.join(root,dir)).filter(f=>f.endsWith('.json')).map(f=>read(`${dir}/${f}`));
const base = (process.env.BASE_PATH || '').replace(/\/$/,'');
if (base && !/^\/[a-zA-Z0-9_-]+$/.test(base)) throw new Error('BASE_PATH must be a single absolute path segment.');
const origin = (process.env.SITE_URL || 'https://www.eomasters.org').replace(/\/$/,'');
const preview = process.env.PREVIEW === 'true';
const out=path.resolve(root,'dist');
if (path.dirname(out)!==root || path.basename(out)!=='dist') throw new Error('Unsafe build output path');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(root,'public'),out,{recursive:true});
const b=read('content/branding.json');
const posts=files('content/posts').sort((a,b)=>b.date.localeCompare(a.date));
const newsletters=files('content/newsletters').sort((a,b)=>b.number-a.number);
const pages=Object.fromEntries(files('content/pages').map(p=>[p.path,p]));
const db=read('content/eo-data.json');
export const escape=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const e=escape;
const canonicalPath=p=>p==='/'?'/':p.replace(/\/$/,'')+'/';
const date=d=>d?new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}):'';
const text=html=>html.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const image=(src,alt,cl='')=>`<img src="${e(src)}" alt="${e(alt)}" loading="lazy" decoding="async"${cl?` class="${cl}"`:''}>`;
const socialLinks=[
 {name:'LinkedIn',url:'https://www.linkedin.com/company/eomasters',icon:'linkedin'},
 {name:'Bluesky',url:'https://bsky.app/profile/eomasters.org',icon:'bluesky'},
 {name:'Mastodon',url:'https://mastodon.green/@EOMasters',icon:'mastodon',rel:'me'},
 {name:'Medium',url:'https://medium.com/@eomasters'}
];
const socialIcons=Object.fromEntries(socialLinks.filter(s=>s.icon).map(s=>[s.icon,fs.readFileSync(path.join(root,'public/assets/social',s.icon+'.svg'),'utf8').replace('<svg ','<svg aria-hidden="true" focusable="false" ')]));
const social=({includeMedium=true,icons=false}={})=>`<div class="social-links">${socialLinks.filter(s=>includeMedium||s.name!=='Medium').map(s=>`<a href="${s.url}"${s.rel?` rel="${s.rel}"`:''}>${icons&&s.icon?socialIcons[s.icon]:''}<span>${s.name}</span></a>`).join('')}</div>`;
const nav=(name,links)=>`<details class="nav-group"><summary>${name}</summary><div class="dropdown">${links.map(([t,h])=>`<a href="${h}">${t}</a>`).join('')}</div></details>`;
const header=`<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/"><img src="${b.logo}" width="85" height="85" alt="EOMasters superheroes"><span>EOMasters</span></a><div class="header-navigation"><nav class="main-nav" aria-label="Main navigation">${nav('Software',[['All software','/eom-software/'],['EOMasters Toolbox','/eom-software/eomtbx/'],['DAVALIEN','/eom-software/davalien/'],['Software & Training','/eom-software/service/']])}${nav('Knowledge',[['All resources','/knowledge/'],['Tutorials','/knowledge/tutorials/'],['EOpedia','/knowledge/eopedia/'],['Coastal Map','/knowledge/coastalmap/'],['EO Data DB','/eoddb/']])}${nav('Community',[['Community','/community/'],['Blog','/blog/'],['Newsletter archive','/newsletter-archive/'],['Testimonials','/testimonials/']])}</nav><nav class="header-social" aria-label="Social media">${social({includeMedium:false,icons:true})}</nav></div></div></header>`;
const footer=`<footer class="site-footer"><div class="wrap"><div class="footer-main"><div><p class="footer-brand">EOMasters</p><p>Mastering Earth Observation.</p>${social({includeMedium:false})}</div><nav class="footer-links" aria-label="Footer"><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/imprint/">Imprint</a><a href="/terms-conditions/">Terms & Conditions</a><a href="/data-protection-policy-gdpr/">Privacy</a></nav></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Marco Peters</span><span>Contains modified Copernicus Sentinel data.</span></div></div></footer>`;
// Apply the same external-link behaviour to navigation and imported content.
function externalLinks(html){
 const localHosts=new Set(['eomasters.org','www.eomasters.org',new URL(origin).hostname]);
 return html.replace(/<a\b[^>]*>/gi,tag=>{
  const href=tag.match(/\shref\s*=\s*(["'])(.*?)\1/i)?.[2];
  if(!href || !/^(?:https?:)?\/\//i.test(href) || (URL.canParse(href,origin) && localHosts.has(new URL(href,origin).hostname))) return tag;
  const rel=tag.match(/\srel\s*=\s*(["'])(.*?)\1/i)?.[2] || '';
  const tokens=new Set(rel.split(/\s+/).filter(Boolean));
  tokens.add('noopener');
  return tag.replace(/\s(?:target|rel)\s*=\s*(["']).*?\1/gi,'').replace(/>$/,` target="_blank" rel="${[...tokens].join(' ')}">`);
 });
}
const routes=[];
function write(route,title,description,body,{article,cls='',noindex=false}={}){
 const url=origin+canonicalPath(route);const schema=article?`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'BlogPosting',headline:title,datePublished:article.date,dateModified:article.modified||article.date,author:{'@type':'Person',name:'Marco Peters'},mainEntityOfPage:url,url,...(article.image?{image:origin+article.image}:{})}).replaceAll('<','\\u003c')}</script>`:'';
 const comparisonAssets=body.includes('class="image-comparison"')?'<link rel="stylesheet" href="/vendor/juxtapose/juxtapose.css"><script src="/vendor/juxtapose/juxtapose.js" defer></script>':'';
 let html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)}${title==='EOMasters | Mastering Earth Observation'?'':' | EOMasters'}</title><meta name="description" content="${e(description)}"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#242424"><link rel="canonical" href="${e(url)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:url" content="${e(url)}"><meta name="referrer" content="strict-origin-when-cross-origin">${preview||noindex?'<meta name="robots" content="noindex, nofollow">':''}<link rel="icon" href="${b.logo}" type="image/webp">${comparisonAssets}<link rel="stylesheet" href="/styles.css"><script src="/site.js" defer></script>${schema}</head><body>${header}<main id="main" class="wrap ${cls}">${body}</main>${footer}</body></html>`;
 html=externalLinks(html);
 html=html.replace(/(href|src)="\/(?!\/)([^"#]*)/g,(_,attr,p)=>`${attr}="${base}/${p}`);
 const dest=route==='/404.html'?path.join(out,'404.html'):path.join(out,route,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);routes.push({path:route,title,file:path.relative(out,dest)});
}
const head=(title,desc='',section='')=>`<div class="page-head">${section?`<p class="eyebrow">${section}</p>`:''}<h1>${e(title)}</h1>${desc?`<p class="lead">${desc}</p>`:''}</div>`;
const card=(title,desc,href,src='',contain=false,linkImage=false)=>`<article class="card">${src?(linkImage?`<a class="card-image-link" href="${href}">${image(src,title,contain?'contain':'')}</a>`:image(src,title,contain?'contain':'')):''}<div class="card-body"><h2><a href="${href}">${title}</a></h2><p>${desc}</p><a href="${href}">Explore ${title==='EOMasters Toolbox'?'the toolbox':title}</a></div></article>`;
const postCard=p=>`<article class="card" data-categories="${e(JSON.stringify(p.categories))}">${p.image?`<a href="${p.path}/" tabindex="-1" aria-hidden="true">${image(p.image,'')}</a>`:''}<div class="card-body"><time datetime="${e(p.date)}">${date(p.date)}</time><h2><a href="${p.path}/">${e(p.title)}</a></h2><p>${e(text(p.description||p.html).slice(0,150))}…</p><a href="${p.path}/">Read article</a></div></article>`;
const service=()=>`<aside class="service-note"><h2>Need software tailored to your work?</h2><p>Marco Peters provides freelance software development, Earth observation expertise and SNAP training. Explore his experience and services on his personal website.</p><a class="button" href="https://www.eomp.info/">Meet Marco at eomp.info</a></aside>`;
function pageImage(slug,index=0){return [...pages[slug].html.matchAll(/<img[^>]+src="([^"]+)"/g)][index]?.[1]||'';}
write('/','EOMasters | Mastering Earth Observation','Software, knowledge and community for Earth observation and remote sensing.',`<section class="hero"><img src="${b.hero}" alt="Satellite view of a coastal landscape" fetchpriority="high"><div class="hero-copy"><p class="eyebrow">Mastering Earth Observation</p><h1>Welcome EO-Master!</h1><p>This is a place for remote sensing enthusiasts and Earth observation masters — and those who want to become one.</p></div></section><section class="pillars" aria-label="Explore EOMasters">${[['Software',b.software,'Tools for SNAP, scientific processing and data validation. Make your daily work with Earth observation data easier.','/eom-software/'],['Knowledge',b.knowledge,'Tutorials, practical resources and ideas to deepen your understanding of Earth observation.','/knowledge/'],['Community',b.community,'Explore the blog, browse the newsletter archive and connect with EOMasters on social media.','/community/']].map(([t,img,d,h])=>`<article class="pillar">${image(img,'')}<h2><a href="${h}">${t}</a></h2><p>${d}</p><a href="${h}">Explore ${t.toLowerCase()}</a></article>`).join('')}</section><p class="statement">Software. Knowledge. Community.<br>Be faster, be more productive, have more fun with Earth observation.</p><div class="section-heading"><h2>From the blog</h2><a href="/blog/">All articles</a></div><div class="grid">${posts.slice(0,3).map(postCard).join('')}</div>${service()}`);
write('/eom-software','Software','Open-source tools for Earth observation, SNAP and data validation.',head('Software','Tools that make working with Earth observation data more productive.')+`<div class="grid two">${card('EOMasters Toolbox','New features and scientific tools for ESA SNAP, including Python development and Sentinel-2 super-resolution.','/eom-software/eomtbx/',pageImage('/eom-software/eomtbx'),true,true)}${card('DAVALIEN','Define expected processing results and validate Earth observation data with repeatable tests.','/eom-software/davalien/',pageImage('/eom-software/davalien'),true,true)}</div>`+service());
write('/knowledge','Knowledge','Tutorials, EOpedia, Coastal Map and an Earth observation data directory.',head('Knowledge','Practical resources for remote sensing enthusiasts and Earth observation masters.')+`<div class="grid two">${card('Tutorials','Videos about software use, development and Earth observation.','/knowledge/tutorials/',pageImage('/knowledge/tutorials',1))}${card('EOpedia','Essential Earth observation knowledge with links to useful resources.','/knowledge/eopedia/',pageImage('/knowledge/eopedia'),true)}${card('Coastal Map','Global coastal indicators at approximately 10-metre resolution.','/knowledge/coastalmap/',pageImage('/knowledge/coastalmap'),true)}${card('EO Data DB','Find instruments and data sources by sensor type, theme and platform.','/eoddb/',pageImage('/knowledge',3))}</div>`);
write('/community','Community','Read the EOMasters blog, explore the newsletter archive and connect on social media.',head('Community','Ideas, experience and perspectives from the Earth observation community.')+`<div class="grid">${card('Blog','Personal opinions, ideas and thoughts on Earth observation, remote sensing and space science.','/blog/')}${card('Newsletter archive','Browse all 41 issues of the EOMasters newsletter, published from 2023 to 2025.','/newsletter-archive/')}${card('Testimonials','What others say about EOMasters tutorials, software and support.','/testimonials/')}</div><section class="service-note"><h2>Follow EOMasters</h2><p>Keep up with software releases, new articles and developments in Earth observation.</p>${social()}</section>`);
write('/eom-software/service','Software & Training','Freelance software development and SNAP training by Marco Peters.',head('Software & Training','Earth observation expertise for your next project.','Work with Marco')+`<div class="feature">${image(pageImage('/eom-software/service'),'Custom software development')}<div><h2>From an idea to working software.</h2><p>I’m Marco Peters, a freelance software developer with more than 20 years of experience in Earth observation and a long history of developing ESA SNAP and its predecessor BEAM.</p><p>I help with custom SNAP extensions, data readers, processing algorithms, scientific applications and training. My freelance services and professional background now have their own home.</p><a class="button primary" href="https://www.eomp.info/">Visit eomp.info</a></div></div>`);
write('/about','About EOMasters','EOMasters is run by Marco Peters, an Earth observation software developer.',head('About EOMasters','A place for Earth observation masters — and those who want to become one.')+`<div class="feature">${image(pageImage('/about'),'Marco Peters')}<div><h2>Hello, I’m Marco.</h2><p>I’m a software developer with more than 20 years of experience in Earth observation. I started EOMasters to share useful software, practical knowledge and ideas with the remote sensing community.</p><p>Explore the tools, learn something new, or read the story behind the project in <a href="/post/hello-eo-masters/">Hello EO-Masters!</a></p><p>For my freelance work, professional background and services, visit <a href="https://www.eomp.info/">eomp.info</a>.</p></div></div>`);
write('/contact','Contact','Contact Marco Peters at EOMasters.',head('Contact','I’m always happy to hear from other EO-Masters.')+`<div class="grid two"><section class="card"><div class="card-body"><h2>Get in touch</h2><p><a href="mailto:info@eomasters.org">info@eomasters.org</a><br><a href="tel:+494036932689">+49 40 36932689</a></p><p>Questions, feedback or an idea to share? Send me an email or give me a call.</p></div></section><section class="card"><div class="card-body"><h2>Keep in touch</h2><p>Follow new articles, tools and developments.</p>${social()}</div></section></div>`+service());
write('/knowledge/tutorials','Tutorials','Video tutorials about SNAP, Earth observation and software development.',head('Tutorials','Learn about Earth observation, using SNAP and developing your own software.')+`<div class="grid two">${card('Video tutorials','Explore software workflows, development topics and Earth observation techniques.','https://www.youtube.com/playlist?list=PLS_xBjOThHFWd8Rq8bn-F1d6pKYqTiQH3',pageImage('/knowledge/tutorials',1))}${card('Mini tutorials','Short videos explaining a specific topic — a knowledge snack in between.','https://www.youtube.com/playlist?list=PLS_xBjOThHFUWQnaTBi95ajrqlZRgluUz',pageImage('/knowledge/tutorials',2))}</div><p class="notice">The videos open on YouTube.</p>`);
for(const slug of ['/eom-software/eomtbx','/eom-software/davalien','/knowledge/eopedia','/knowledge/coastalmap','/testimonials','/imprint','/terms-conditions']){
 const p=pages[slug];let html=p.html.replace(/<h1\b[^>]*>[\s\S]*?<\/h1>/,'');
 html=html.replace(/ or post on the <a[^>]*>EOMasters forum<\/a>/g,'').replace('WSG84','WGS84');
 const isToolbox=slug==='/eom-software/eomtbx';
 write(slug,p.title,p.description||text(html).slice(0,160),head(p.title,'',slug.startsWith('/eom-software')?'Software':slug.startsWith('/knowledge')?'Knowledge':'')+`<div class="${isToolbox?'toolbox-showcase':'prose'}">${html}</div>`,{cls:isToolbox?'toolbox-page':''});
}
const privacy=fs.readFileSync(path.join(root,'content/privacy.html'),'utf8');
write('/data-protection-policy-gdpr','Privacy policy','Privacy information for the EOMasters website.',head('Privacy policy')+`<div class="prose">${privacy}</div>`);
for(const p of posts){write(p.path,p.title,p.description||text(p.html).slice(0,160),`<header class="page-head article-head"><p class="crumb"><a href="/blog/">Blog</a></p><h1>${e(p.title)}</h1><p class="meta">Marco Peters · <time datetime="${e(p.date)}">${date(p.date)}</time></p></header><article class="prose">${p.html}<div class="article-end"><a class="back-link" href="/blog/">Back to all articles</a></div></article>`,{article:p});}
const categories=[['earth-observation','Earth observation'],['space-science','Space science'],['opinion','Opinion'],['software','Software'],['sunstainability','Sustainability']];
write('/blog','Blog','Articles about Earth observation, remote sensing, software and space science.',head('Blog','Personal opinions, ideas and thoughts on Earth observation, remote sensing and space science.')+`<div class="blog-tools"><label for="blog-category">Browse by topic</label><select id="blog-category"><option value="">All articles</option>${categories.map(([s,t])=>`<option value="${s}">${t}</option>`).join('')}</select></div><div class="grid">${posts.map(postCard).join('')}</div>`);
for(const [slug,label] of categories){write('/blog/categories/'+slug,label+' articles','EOMasters articles about '+label.toLowerCase()+'.',head(label)+`<p><a href="/blog/">All articles</a></p><div class="grid">${posts.filter(p=>p.categories.includes(slug)).map(postCard).join('')}</div>`);}
write('/newsletter-archive','Newsletter archive','All 41 archived editions of the EOMasters newsletter.',head('Newsletter archive','A hand-picked collection of news from Earth observation and remote sensing. The newsletter concluded in February 2025; all 41 issues remain available here.')+`<div class="archive-list">${newsletters.map(n=>`<article class="archive-entry"><time class="meta" datetime="${e(n.date)}">${date(n.date)}</time><h2><a href="${n.path}/">${e(n.title)}</a></h2><a href="${n.path}/">Read issue</a></article>`).join('')}</div>`);
for(const n of newsletters){write(n.path,n.title,n.description,`<header class="page-head newsletter-head"><p class="crumb"><a href="/newsletter-archive/">Newsletter archive</a></p></header><article class="prose newsletter">${n.html}<p class="article-end"><a href="/newsletter-archive/">Back to the archive</a></p></article>`);}
const filterGroup=(key,label)=>`<fieldset><legend>${label}</legend><div class="${key==='platform'?'platforms':''}">${[...new Set(db.flatMap(d=>d[key]))].sort().map(v=>`<label><input type="checkbox" name="${key}" value="${e(v)}">${e(v)}</label>`).join('')}</div></fieldset>`;
const dbcard=d=>`<article class="db-card" data-sensor="${e(JSON.stringify(d.sensor))}" data-theme="${e(JSON.stringify(d.theme))}" data-platform="${e(JSON.stringify(d.platform))}" data-active="${d.active}"><h2>${e(d.name)}</h2><p class="tags">${e(d.sensor.join(' · '))}</p><p>${e(d.description)}</p><dl><div><dt>Platforms</dt><dd>${e(d.platform.join(', '))}</dd></div><div><dt>Themes</dt><dd>${e(d.theme.join(', '))}</dd></div><div><dt>In operation</dt><dd>${d.active?'Yes':'No'}</dd></div></dl><div class="table-scroll"><table class="sources"><caption>Data sources for ${e(d.name)}</caption><thead><tr><th scope="col">Source</th><th scope="col">Free</th><th scope="col">Apply</th><th scope="col">Pay</th></tr></thead><tbody>${d.sources.map(s=>`<tr><td><a href="${e(s.url)}">${e(s.name)}</a></td><td>${s.free?'Yes':'No'}</td><td>${s.apply?'Yes':'No'}</td><td>${s.pay?'Yes':'No'}</td></tr>`).join('')}</tbody></table></div></article>`;
write('/eoddb','EO Data DB','Find Earth observation instruments and data sources by sensor type, theme and platform.',head('EO Data DB','Find Earth observation data by instrument, platform and application.')+`<div class="db-layout"><form class="filters" id="db-filters" aria-label="Filter instruments"><div class="filter-groups">${filterGroup('sensor','Sensor type')}${filterGroup('theme','Theme')}${filterGroup('platform','Platform')}</div><label><input type="checkbox" name="active">In operation only</label><button type="reset">Reset filters</button></form><section aria-label="Instruments"><p id="result-count" class="result-count" role="status" aria-live="polite">${db.length} instruments</p><noscript><p>Enable JavaScript to use the filters. All instruments are listed below.</p></noscript><p class="empty" id="no-results" hidden>No instruments match these filters. Try removing a filter.</p>${db.map(dbcard).join('')}</section></div><aside class="service-note"><h2>Missing an entry?</h2><p>Share a useful data source or suggest a correction.</p><a href="mailto:info@eomasters.org?subject=EO%20Data%20DB%20suggestion">Email your suggestion</a></aside>`);
write('/404.html','Page not found','This page could not be found on EOMasters.',head('This page could not be found.','Explore the software, knowledge resources and blog to find what you need.')+`<div class="actions"><a class="button primary" href="/">Go to the homepage</a><a class="button" href="/blog/">Browse the blog</a></div>`,{noindex:true});
// Former product URLs remain useful after the Pro/Basic products were consolidated.
const redirects={'/eom-software/eomtbx-pro':'/eom-software/eomtbx/','/eom-software/eomtbx-basic':'/eom-software/eomtbx/','/eomtbx':'/eom-software/eomtbx/','/davalien':'/eom-software/davalien/','/eomasters':'/about/','/copy-of-tutorials':'/knowledge/tutorials/','/custom':'/eom-software/service/'};
for(const [from,to] of Object.entries(redirects)){const dest=path.join(out,from,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,`<!doctype html><html lang="en"><meta charset="utf-8"><title>EOMasters Toolbox</title><meta http-equiv="refresh" content="0;url=${base+to}"><link rel="canonical" href="${origin+to}"><p><a href="${base+to}">Continue to EOMasters Toolbox</a></p></html>`);routes.push({path:from,file:path.relative(out,dest),redirect:to});}
fs.writeFileSync(path.join(out,'.nojekyll'),'');
fs.writeFileSync(path.join(out,'robots.txt'),preview?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.filter(r=>r.path!=='/404.html'&&!r.redirect).map(r=>`<url><loc>${e(origin+canonicalPath(r.path))}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(path.join(root,'content/routes.json'),JSON.stringify(routes,null,2));
console.log(`Built ${routes.length} routes: ${posts.length} blog posts, ${newsletters.length} newsletters, ${db.length} instruments.`);
